// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Server/ffProto.proto

/*
Package ffProto is a generated protocol buffer package.

It is generated from these files:
	Server/ffProto.proto

It has these top-level messages:
	StAccountData
	MsgServerRegister
	MsgServerKeepAlive
	MsgPrepareLoginPlatformUniqueID
	MsgLoginPlatformUniqueID
	MsgLoginPlatformSidToken
	MsgReLogin
	MsgKick
	MsgEnterGameWorld
	MsgAgentDisConnect
	MsgKeepAlive
*/
package ffProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_ServerRegister               MessageType = 0
	MessageType_ServerKeepAlive              MessageType = 1
	MessageType_PrepareLoginPlatformUniqueID MessageType = 2
	MessageType_LoginPlatformUniqueID        MessageType = 3
	MessageType_LoginPlatformSidToken        MessageType = 4
	MessageType_ReLogin                      MessageType = 5
	MessageType_Kick                         MessageType = 6
	MessageType_EnterGameWorld               MessageType = 7
	MessageType_AgentDisConnect              MessageType = 8
	MessageType_KeepAlive                    MessageType = 9
)

var MessageType_name = map[int32]string{
	0: "ServerRegister",
	1: "ServerKeepAlive",
	2: "PrepareLoginPlatformUniqueID",
	3: "LoginPlatformUniqueID",
	4: "LoginPlatformSidToken",
	5: "ReLogin",
	6: "Kick",
	7: "EnterGameWorld",
	8: "AgentDisConnect",
	9: "KeepAlive",
}
var MessageType_value = map[string]int32{
	"ServerRegister":               0,
	"ServerKeepAlive":              1,
	"PrepareLoginPlatformUniqueID": 2,
	"LoginPlatformUniqueID":        3,
	"LoginPlatformSidToken":        4,
	"ReLogin":                      5,
	"Kick":                         6,
	"EnterGameWorld":               7,
	"AgentDisConnect":              8,
	"KeepAlive":                    9,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Generated by the msggen.py message compiler.
type StAccountData struct {
	IsFirst    bool    `protobuf:"varint,1,opt,name=isFirst" json:"isFirst,omitempty"`
	ServerTime int32   `protobuf:"varint,2,opt,name=serverTime" json:"serverTime,omitempty"`
	ServerZone int32   `protobuf:"varint,3,opt,name=serverZone" json:"serverZone,omitempty"`
	Name       string  `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	BaseKeys   []int32 `protobuf:"varint,5,rep,packed,name=baseKeys" json:"baseKeys,omitempty"`
	BaseDatas  []int32 `protobuf:"varint,6,rep,packed,name=baseDatas" json:"baseDatas,omitempty"`
}

func (m *StAccountData) Reset()                    { *m = StAccountData{} }
func (m *StAccountData) String() string            { return proto.CompactTextString(m) }
func (*StAccountData) ProtoMessage()               {}
func (*StAccountData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StAccountData) GetIsFirst() bool {
	if m != nil {
		return m.IsFirst
	}
	return false
}

func (m *StAccountData) GetServerTime() int32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

func (m *StAccountData) GetServerZone() int32 {
	if m != nil {
		return m.ServerZone
	}
	return 0
}

func (m *StAccountData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StAccountData) GetBaseKeys() []int32 {
	if m != nil {
		return m.BaseKeys
	}
	return nil
}

func (m *StAccountData) GetBaseDatas() []int32 {
	if m != nil {
		return m.BaseDatas
	}
	return nil
}

type MsgServerRegister struct {
	ServerType string `protobuf:"bytes,1,opt,name=serverType" json:"serverType,omitempty"`
	ServerID   int32  `protobuf:"varint,2,opt,name=serverID" json:"serverID,omitempty"`
}

func (m *MsgServerRegister) Reset()                    { *m = MsgServerRegister{} }
func (m *MsgServerRegister) String() string            { return proto.CompactTextString(m) }
func (*MsgServerRegister) ProtoMessage()               {}
func (*MsgServerRegister) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MsgServerRegister) GetServerType() string {
	if m != nil {
		return m.ServerType
	}
	return ""
}

func (m *MsgServerRegister) GetServerID() int32 {
	if m != nil {
		return m.ServerID
	}
	return 0
}

type MsgServerKeepAlive struct {
}

func (m *MsgServerKeepAlive) Reset()                    { *m = MsgServerKeepAlive{} }
func (m *MsgServerKeepAlive) String() string            { return proto.CompactTextString(m) }
func (*MsgServerKeepAlive) ProtoMessage()               {}
func (*MsgServerKeepAlive) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type MsgPrepareLoginPlatformUniqueID struct {
	SubChannel        string `protobuf:"bytes,1,opt,name=subChannel" json:"subChannel,omitempty"`
	UUIDPlatformBound string `protobuf:"bytes,2,opt,name=UUIDPlatformBound" json:"UUIDPlatformBound,omitempty"`
	UUIDPlatformLogin string `protobuf:"bytes,3,opt,name=UUIDPlatformLogin" json:"UUIDPlatformLogin,omitempty"`
	RandomSalt        string `protobuf:"bytes,4,opt,name=randomSalt" json:"randomSalt,omitempty"`
	Timestamp         int32  `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	Status            int32  `protobuf:"varint,6,opt,name=status" json:"status,omitempty"`
	Result            int32  `protobuf:"varint,7,opt,name=result" json:"result,omitempty"`
}

func (m *MsgPrepareLoginPlatformUniqueID) Reset()                    { *m = MsgPrepareLoginPlatformUniqueID{} }
func (m *MsgPrepareLoginPlatformUniqueID) String() string            { return proto.CompactTextString(m) }
func (*MsgPrepareLoginPlatformUniqueID) ProtoMessage()               {}
func (*MsgPrepareLoginPlatformUniqueID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MsgPrepareLoginPlatformUniqueID) GetSubChannel() string {
	if m != nil {
		return m.SubChannel
	}
	return ""
}

func (m *MsgPrepareLoginPlatformUniqueID) GetUUIDPlatformBound() string {
	if m != nil {
		return m.UUIDPlatformBound
	}
	return ""
}

func (m *MsgPrepareLoginPlatformUniqueID) GetUUIDPlatformLogin() string {
	if m != nil {
		return m.UUIDPlatformLogin
	}
	return ""
}

func (m *MsgPrepareLoginPlatformUniqueID) GetRandomSalt() string {
	if m != nil {
		return m.RandomSalt
	}
	return ""
}

func (m *MsgPrepareLoginPlatformUniqueID) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MsgPrepareLoginPlatformUniqueID) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *MsgPrepareLoginPlatformUniqueID) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MsgLoginPlatformUniqueID struct {
	TokenCustom string `protobuf:"bytes,1,opt,name=tokenCustom" json:"tokenCustom,omitempty"`
	DeviceGUID  string `protobuf:"bytes,2,opt,name=deviceGUID" json:"deviceGUID,omitempty"`
	UUIDLogin   uint64 `protobuf:"varint,3,opt,name=UUIDLogin" json:"UUIDLogin,omitempty"`
	Result      int32  `protobuf:"varint,4,opt,name=result" json:"result,omitempty"`
}

func (m *MsgLoginPlatformUniqueID) Reset()                    { *m = MsgLoginPlatformUniqueID{} }
func (m *MsgLoginPlatformUniqueID) String() string            { return proto.CompactTextString(m) }
func (*MsgLoginPlatformUniqueID) ProtoMessage()               {}
func (*MsgLoginPlatformUniqueID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MsgLoginPlatformUniqueID) GetTokenCustom() string {
	if m != nil {
		return m.TokenCustom
	}
	return ""
}

func (m *MsgLoginPlatformUniqueID) GetDeviceGUID() string {
	if m != nil {
		return m.DeviceGUID
	}
	return ""
}

func (m *MsgLoginPlatformUniqueID) GetUUIDLogin() uint64 {
	if m != nil {
		return m.UUIDLogin
	}
	return 0
}

func (m *MsgLoginPlatformUniqueID) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MsgLoginPlatformSidToken struct {
	TokenPlatform string `protobuf:"bytes,1,opt,name=tokenPlatform" json:"tokenPlatform,omitempty"`
	DeviceGUID    string `protobuf:"bytes,2,opt,name=deviceGUID" json:"deviceGUID,omitempty"`
	UUIDLogin     uint64 `protobuf:"varint,3,opt,name=UUIDLogin" json:"UUIDLogin,omitempty"`
	Result        int32  `protobuf:"varint,4,opt,name=result" json:"result,omitempty"`
}

func (m *MsgLoginPlatformSidToken) Reset()                    { *m = MsgLoginPlatformSidToken{} }
func (m *MsgLoginPlatformSidToken) String() string            { return proto.CompactTextString(m) }
func (*MsgLoginPlatformSidToken) ProtoMessage()               {}
func (*MsgLoginPlatformSidToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MsgLoginPlatformSidToken) GetTokenPlatform() string {
	if m != nil {
		return m.TokenPlatform
	}
	return ""
}

func (m *MsgLoginPlatformSidToken) GetDeviceGUID() string {
	if m != nil {
		return m.DeviceGUID
	}
	return ""
}

func (m *MsgLoginPlatformSidToken) GetUUIDLogin() uint64 {
	if m != nil {
		return m.UUIDLogin
	}
	return 0
}

func (m *MsgLoginPlatformSidToken) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MsgReLogin struct {
	CheckData  string `protobuf:"bytes,1,opt,name=checkData" json:"checkData,omitempty"`
	DeviceGUID string `protobuf:"bytes,2,opt,name=deviceGUID" json:"deviceGUID,omitempty"`
	Result     int32  `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
}

func (m *MsgReLogin) Reset()                    { *m = MsgReLogin{} }
func (m *MsgReLogin) String() string            { return proto.CompactTextString(m) }
func (*MsgReLogin) ProtoMessage()               {}
func (*MsgReLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MsgReLogin) GetCheckData() string {
	if m != nil {
		return m.CheckData
	}
	return ""
}

func (m *MsgReLogin) GetDeviceGUID() string {
	if m != nil {
		return m.DeviceGUID
	}
	return ""
}

func (m *MsgReLogin) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MsgKick struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *MsgKick) Reset()                    { *m = MsgKick{} }
func (m *MsgKick) String() string            { return proto.CompactTextString(m) }
func (*MsgKick) ProtoMessage()               {}
func (*MsgKick) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MsgKick) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MsgEnterGameWorld struct {
	ServerID  int32  `protobuf:"varint,1,opt,name=serverID" json:"serverID,omitempty"`
	UUIDLogin uint64 `protobuf:"varint,2,opt,name=UUIDLogin" json:"UUIDLogin,omitempty"`
	Result    int32  `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
}

func (m *MsgEnterGameWorld) Reset()                    { *m = MsgEnterGameWorld{} }
func (m *MsgEnterGameWorld) String() string            { return proto.CompactTextString(m) }
func (*MsgEnterGameWorld) ProtoMessage()               {}
func (*MsgEnterGameWorld) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MsgEnterGameWorld) GetServerID() int32 {
	if m != nil {
		return m.ServerID
	}
	return 0
}

func (m *MsgEnterGameWorld) GetUUIDLogin() uint64 {
	if m != nil {
		return m.UUIDLogin
	}
	return 0
}

func (m *MsgEnterGameWorld) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MsgAgentDisConnect struct {
}

func (m *MsgAgentDisConnect) Reset()                    { *m = MsgAgentDisConnect{} }
func (m *MsgAgentDisConnect) String() string            { return proto.CompactTextString(m) }
func (*MsgAgentDisConnect) ProtoMessage()               {}
func (*MsgAgentDisConnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type MsgKeepAlive struct {
	Number int32 `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
}

func (m *MsgKeepAlive) Reset()                    { *m = MsgKeepAlive{} }
func (m *MsgKeepAlive) String() string            { return proto.CompactTextString(m) }
func (*MsgKeepAlive) ProtoMessage()               {}
func (*MsgKeepAlive) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *MsgKeepAlive) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func init() {
	proto.RegisterType((*StAccountData)(nil), "StAccountData")
	proto.RegisterType((*MsgServerRegister)(nil), "MsgServerRegister")
	proto.RegisterType((*MsgServerKeepAlive)(nil), "MsgServerKeepAlive")
	proto.RegisterType((*MsgPrepareLoginPlatformUniqueID)(nil), "MsgPrepareLoginPlatformUniqueID")
	proto.RegisterType((*MsgLoginPlatformUniqueID)(nil), "MsgLoginPlatformUniqueID")
	proto.RegisterType((*MsgLoginPlatformSidToken)(nil), "MsgLoginPlatformSidToken")
	proto.RegisterType((*MsgReLogin)(nil), "MsgReLogin")
	proto.RegisterType((*MsgKick)(nil), "MsgKick")
	proto.RegisterType((*MsgEnterGameWorld)(nil), "MsgEnterGameWorld")
	proto.RegisterType((*MsgAgentDisConnect)(nil), "MsgAgentDisConnect")
	proto.RegisterType((*MsgKeepAlive)(nil), "MsgKeepAlive")
	proto.RegisterEnum("MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("Server/ffProto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 604 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xc7, 0x7f, 0xce, 0x7f, 0x4f, 0x7f, 0x05, 0x77, 0x29, 0xc8, 0xa0, 0x0a, 0x82, 0x85, 0x50,
	0x84, 0x10, 0x1c, 0x78, 0x82, 0xd2, 0x40, 0x55, 0x15, 0x8b, 0xca, 0x69, 0x84, 0xc4, 0x6d, 0xe3,
	0x4c, 0xdd, 0x55, 0xed, 0xdd, 0xb0, 0xbb, 0xae, 0xd4, 0x67, 0xe0, 0xc6, 0x81, 0x57, 0xe1, 0x69,
	0x78, 0x17, 0xb4, 0x6b, 0x3b, 0xb6, 0xd3, 0x00, 0x27, 0x2e, 0x91, 0xe7, 0x3b, 0xe3, 0x9d, 0xcf,
	0x8c, 0xf7, 0x1b, 0xd8, 0x9f, 0xa1, 0xbc, 0x46, 0xf9, 0xfa, 0xe2, 0xe2, 0x4c, 0x0a, 0x2d, 0x5e,
	0xad, 0xcc, 0x6f, 0xf0, 0xc3, 0x81, 0xdd, 0x99, 0x3e, 0x8c, 0x63, 0x91, 0x73, 0x3d, 0xa5, 0x9a,
	0x12, 0x1f, 0x86, 0x4c, 0xbd, 0x67, 0x52, 0x69, 0xdf, 0x19, 0x3b, 0x93, 0x51, 0x54, 0x85, 0xe4,
	0x31, 0x80, 0xb2, 0x67, 0x9c, 0xb3, 0x0c, 0xfd, 0xce, 0xd8, 0x99, 0xf4, 0xa3, 0x86, 0x52, 0xe7,
	0x3f, 0x0b, 0x8e, 0x7e, 0xb7, 0x99, 0x37, 0x0a, 0x21, 0xd0, 0xe3, 0x34, 0x43, 0xbf, 0x37, 0x76,
	0x26, 0x6e, 0x64, 0x9f, 0xc9, 0x23, 0x18, 0x2d, 0xa8, 0xc2, 0x53, 0xbc, 0x51, 0x7e, 0x7f, 0xdc,
	0x9d, 0xf4, 0xa3, 0x75, 0x4c, 0x0e, 0xc0, 0x35, 0xcf, 0x86, 0x4a, 0xf9, 0x03, 0x9b, 0xac, 0x85,
	0xe0, 0x23, 0xec, 0x85, 0x2a, 0x29, 0x86, 0x8a, 0x30, 0x61, 0x4a, 0xa3, 0x6c, 0x20, 0xde, 0xac,
	0xd0, 0xf2, 0xbb, 0x51, 0x43, 0x31, 0xed, 0x8a, 0xe8, 0x64, 0x5a, 0x0e, 0xb0, 0x8e, 0x83, 0x7d,
	0x20, 0xeb, 0x03, 0x4f, 0x11, 0x57, 0x87, 0x29, 0xbb, 0xc6, 0xe0, 0x6b, 0x07, 0x9e, 0x84, 0x2a,
	0x39, 0x93, 0xb8, 0xa2, 0x12, 0x3f, 0x88, 0x84, 0xf1, 0xb3, 0x94, 0xea, 0x0b, 0x21, 0xb3, 0x39,
	0x67, 0x5f, 0x72, 0x3c, 0x99, 0xda, 0xae, 0xf9, 0xe2, 0xe8, 0x92, 0x72, 0x8e, 0xe9, 0xba, 0xeb,
	0x5a, 0x21, 0x2f, 0x61, 0x6f, 0x3e, 0x3f, 0x99, 0x56, 0xef, 0xbd, 0x15, 0x39, 0x5f, 0xda, 0xf6,
	0x6e, 0x74, 0x3b, 0xb1, 0x59, 0x6d, 0x5b, 0xda, 0x6d, 0x6e, 0x54, 0xdb, 0x84, 0xe9, 0x2d, 0x29,
	0x5f, 0x8a, 0x6c, 0x46, 0x53, 0x5d, 0xae, 0xb6, 0xa1, 0x98, 0x25, 0x6a, 0x96, 0xa1, 0xd2, 0x34,
	0x5b, 0xf9, 0x7d, 0x3b, 0x72, 0x2d, 0x90, 0x07, 0x30, 0x50, 0x9a, 0xea, 0xdc, 0xec, 0xd7, 0xa4,
	0xca, 0xc8, 0xe8, 0x12, 0x55, 0x9e, 0x6a, 0x7f, 0x58, 0xe8, 0x45, 0x14, 0x7c, 0x73, 0xc0, 0x0f,
	0x55, 0xb2, 0x7d, 0x0d, 0x63, 0xd8, 0xd1, 0xe2, 0x0a, 0xf9, 0x51, 0xae, 0xb4, 0xc8, 0xca, 0x3d,
	0x34, 0x25, 0x03, 0xbb, 0xc4, 0x6b, 0x16, 0xe3, 0xf1, 0xbc, 0xfc, 0x00, 0x6e, 0xd4, 0x50, 0x0c,
	0xac, 0x99, 0xb0, 0x1e, 0xb9, 0x17, 0xd5, 0x42, 0x03, 0xaa, 0xd7, 0x82, 0xfa, 0xbe, 0x05, 0x6a,
	0xc6, 0x96, 0xe7, 0xa6, 0x31, 0x79, 0x06, 0xbb, 0x96, 0xa0, 0x4a, 0x94, 0x58, 0x6d, 0xf1, 0x1f,
	0x81, 0x2d, 0x00, 0x42, 0x95, 0x44, 0xc5, 0xad, 0x31, 0x67, 0xc4, 0x97, 0x18, 0x5f, 0x99, 0xeb,
	0x5b, 0x52, 0xd4, 0xc2, 0x5f, 0x09, 0xea, 0x1e, 0xdd, 0x56, 0x8f, 0xa7, 0x30, 0x0c, 0x55, 0x72,
	0xca, 0xe2, 0xab, 0x46, 0x89, 0xd3, 0x2a, 0x41, 0xeb, 0x94, 0x77, 0x5c, 0xa3, 0x3c, 0xa6, 0x19,
	0x7e, 0x12, 0x32, 0x5d, 0xb6, 0x9c, 0xe0, 0xb4, 0x9d, 0xd0, 0x9e, 0xb6, 0xf3, 0xfb, 0x69, 0xdb,
	0x24, 0x85, 0x7f, 0x0e, 0x13, 0xe4, 0x7a, 0xca, 0xd4, 0x91, 0xe0, 0x1c, 0x63, 0x1d, 0x3c, 0x87,
	0xff, 0x0d, 0x5f, 0xe5, 0x27, 0xf3, 0x36, 0xcf, 0xb3, 0x05, 0xca, 0x0a, 0xb2, 0x88, 0x5e, 0xfc,
	0x74, 0x60, 0x27, 0x44, 0xa5, 0x68, 0x82, 0xd6, 0xa9, 0x04, 0xee, 0xb4, 0xbd, 0xed, 0xfd, 0x47,
	0xee, 0xc1, 0xdd, 0x0d, 0x7b, 0x7a, 0x0e, 0x19, 0xc3, 0xc1, 0x9f, 0xcc, 0xe9, 0x75, 0xc8, 0x43,
	0xb8, 0xbf, 0x3d, 0xd5, 0xbd, 0x95, 0xaa, 0xae, 0x8d, 0xd7, 0x23, 0x3b, 0x30, 0x2c, 0xbf, 0x9c,
	0xd7, 0x27, 0x23, 0xe8, 0x99, 0x15, 0x7b, 0x03, 0xc3, 0xd5, 0xde, 0xa4, 0x37, 0x34, 0x5c, 0x1b,
	0x63, 0x7b, 0x23, 0xb2, 0x0b, 0x6e, 0x8d, 0xe9, 0x2e, 0x06, 0xf6, 0xff, 0xf6, 0xcd, 0xaf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x62, 0xe0, 0x98, 0x1f, 0x87, 0x05, 0x00, 0x00,
}
